#### general settings
name: 00_JDDB_GCP_Net
use_tb_logger: true
model: video_base
distortion: sr
# scale: 4 # GS: without scale for denoising
# gpu_ids: [0,1,2,3,4,5,6,7]
gpu_ids: [0, 1]

#### datasets
datasets:
  train:
    name: REDS4
    mode: Train_JDDB_Data
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: ../Video/Vimeo/vimeo90k_train_GT.lmdb # input training data path
    cache_keys: ~

    N_frames: 5
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 2
    GT_size: 128 # GS: change training dataset to 128
    LQ_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: Test_JDDB_Data
    dataroot_GT: ../datasets/Vid4/GT_small3
    cache_data: True
    N_frames: 5
    padding: new_info

#### network structures
network_G:
  which_model_G: GCPNet
  nf: 64
  nframes: 5
  groups: 8
  w_TSA: True

#### path
path:
  pretrain_model_G: 
  strict_load: false
  # resume_state: ~
  resume_state: 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 0 # 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e4

  manual_seed: 0

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 5e4